# Generated by Django 2.0.7 on 2019-02-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=20)),
                ('d_no', models.CharField(max_length=8)),
                ('locality', models.CharField(max_length=16)),
                ('city', models.CharField(max_length=16)),
                ('district', models.CharField(max_length=16)),
                ('state', models.CharField(max_length=16)),
                ('pincode', models.CharField(max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='employer',
            name='aadharno',
            field=models.CharField(default='0', max_length=12),
        ),
        migrations.AddField(
            model_name='employer',
            name='city',
            field=models.CharField(default='xyz', max_length=200),
        ),
        migrations.AddField(
            model_name='employer',
            name='password',
            field=models.CharField(default='abc', max_length=16),
        ),
        migrations.AddField(
            model_name='employer',
            name='phn_no',
            field=models.CharField(default='123', max_length=10),
        ),
        migrations.AlterField(
            model_name='employer',
            name='name',
            field=models.CharField(default='xyz', max_length=200),
        ),
        migrations.AddField(
            model_name='organisation',
            name='employee',
            field=models.ManyToManyField(to='women.Employer'),
        ),
    ]
